# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Vulmass's Blog
paginate:       5
baseurl:        ""
url:            "vulmass.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Vulmass
  url:          
  email:        nfspark@gmail.com

# Custom vars
version:        1.0.0
github:         https://github.com/Vulmass
repo:         https://github.com/Vulmass/vulmass.github.io.git

# Gems
gems:
  - jekyll-paginate
