# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Bryan Park
paginate:       5
baseurl:        ""
url:            ""

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Bryan Park
  url:          
  email:        nfspark@gmail.com

# Custom vars
version:        1.0.1
github:         https://github.com/BryanParkDev
repo:         https://github.com/BryanParkDev

# Gems
gems:
  - jekyll-paginate
